spring.application.name=spring-demo-cloud-stream
spring.threads.virtual.enabled=true
spring.docker.compose.stop.command=down
# Increase the connection limit if you scale to many instances
spring.rabbitmq.cache.channel.size=100
spring.cloud.function.definition=businessCreatedConsumer;businessCreatedListener
spring.cloud.stream.bindings.business-created.destination=business-created
spring.cloud.stream.bindings.business-created.content-type=application/json
spring.cloud.stream.bindings.businessCreatedConsumer-in-0.destination=business-created
spring.cloud.stream.bindings.businessCreatedConsumer-in-0.content-type=application/json
spring.cloud.stream.bindings.businessCreatedConsumer-in-0.group=business
# How many workers process massages simultaneously?
spring.cloud.stream.bindings.businessCreatedConsumer-in-0.consumer.concurrency=500
spring.cloud.stream.bindings.businessCreatedConsumer-in-0.consumer.max-attempts=3
spring.cloud.stream.bindings.businessCreatedConsumer-in-0.consumer.back-off-multiplier=2.0
spring.cloud.stream.bindings.businessCreatedConsumer-in-0.consumer.back-off-initial-interval=1000
# Prefetch 50 messages at once so the thread never waits for a network roundtrip
spring.cloud.stream.rabbit.bindings.businessCreatedConsumer-in-0.consumer.prefetch=50
# Automatically creates the DLQ
spring.cloud.stream.rabbit.bindings.businessCreatedConsumer-in-0.consumer.auto-bind-dlq=true
# Sends a failed message to DLQ instead of discarding
spring.cloud.stream.rabbit.bindings.businessCreatedConsumer-in-0.consumer.republish-to-dlq=true
# Message stays in DLQ for 5s before potentially being retried
spring.cloud.stream.rabbit.bindings.businessCreatedConsumer-in-0.consumer.dlq-ttl=30000
############################
# class-based consumer
############################
spring.cloud.stream.bindings.businessCreatedListener-in-0.destination=business-created
spring.cloud.stream.bindings.businessCreatedListener-in-0.content-type=application/json
spring.cloud.stream.bindings.businessCreatedListener-in-0.group=business-class-based
# How many workers process massages simultaneously?
spring.cloud.stream.bindings.businessCreatedListener-in-0.consumer.concurrency=500
spring.cloud.stream.bindings.businessCreatedListener-in-0.consumer.max-attempts=3
spring.cloud.stream.bindings.businessCreatedListener-in-0.consumer.back-off-multiplier=2.0
spring.cloud.stream.bindings.businessCreatedListener-in-0.consumer.back-off-initial-interval=1000
# Prefetch 50 messages at once so the thread never waits for a network roundtrip
spring.cloud.stream.rabbit.bindings.businessCreatedListener-in-0.consumer.prefetch=50
# Automatically creates the DLQ
spring.cloud.stream.rabbit.bindings.businessCreatedListener-in-0.consumer.auto-bind-dlq=true
# Sends a failed message to DLQ instead of discarding
spring.cloud.stream.rabbit.bindings.businessCreatedListener-in-0.consumer.republish-to-dlq=true
# Message stays in DLQ for 5s before potentially being retried
spring.cloud.stream.rabbit.bindings.businessCreatedListener-in-0.consumer.dlq-ttl=30000